### PR TITLE
Theme update - new footer design and some issue fixing

### PR DESCRIPTION
**Pull request by HuiSF**
Update all the changes for new footer and About us section.
Also fixed some issues from the tasks at phabricator.wikimedia.org
Updated font smoothing rule for Gecko and Webkit.

### CODE REVIEW

**Comment by prtksxna** [comment]
@HuiSF, thanks for sending a pull request and resolving issues on Phabricator! I guess the code seems good to go!

The only issue I see is the inconsistent use of tabs and spaces. Could you please refer to the [CSS coding conventions](https://www.mediawiki.org/wiki/Manual:Coding_conventions/CSS) and fix this, either by appending to the current commits and force pushing, or by another commit on the same branch that fixes the whitespace.

**Comment by HuiSF** [comment]
Yes. I think my editor use space to instead of tab. I will format it soon

**Comment by prtksxna** [comment]
Thanks @HuiSF :smile:

**Comment by HuiSF** [comment]
Hi @prtksxna ,
I have reformatted CSS code and add a few more patches to fix problem.

**Pull request closed without merging**
